export default [
    {
      id: 1,
      name: "John Doe",
      designation: "Project Manager",
      gender: "Male",
      teamName: "A",
    },
    {
      id: 2,
      name: "Jane Smith",
      designation: "Senior Developer",
      gender: "Female",
      teamName: "A",
    },
    {
      id: 3,
      name: "Mark Johnson",
      designation: "UI/UX Designer",
      gender: "Male",
      teamName: "B",
    },
    {
      id: 4,
      name: "Emily Davis",
      designation: "Frontend Developer",
      gender: "Female",
      teamName: "B",
    },
    {
      id: 5,
      name: "Michael Brown",
      designation: "Backend Developer",
      gender: "Male",
      teamName: "C",
    },
    {
      id: 6,
      name: "Sarah Wilson",
      designation: "QA Tester",
      gender: "Female",
      teamName: "C",
    },
    {
      id: 7,
      name: "David Lee",
      designation: "Marketing Specialist",
      gender: "Male",
      teamName: "D",
    },
    {
      id: 8,
      name: "Lisa Taylor",
      designation: "Content Writer",
      gender: "Female",
      teamName: "D",
    },
    {
      id: 9,
      name: "Andrew Robinson",
      designation: "Data Analyst",
      gender: "Male",
      teamName: "A",
    },
    {
      id: 10,
      name: "Jessica Garcia",
      designation: "Graphic Designer",
      gender: "Female",
      teamName: "A",
    },
    {
      id: 11,
      name: "Kevin Martinez",
      designation: "Systems Administrator",
      gender: "Male",
      teamName: "B",
    },
    {
      id: 12,
      name: "Amanda Hernandez",
      designation: "Business Analyst",
      gender: "Female",
      teamName: "B",
    },
    {
      id: 13,
      name: "Robert Thomas",
      designation: "Sales Representative",
      gender: "Male",
      teamName: "C",
    },
    {
      id: 14,
      name: "Megan White",
      designation: "Customer Support Specialist",
      gender: "Female",
      teamName: "C",
    },
    {
      id: 15,
      name: "Daniel Harris",
      designation: "Product Manager",
      gender: "Male",
      teamName: "D",
    },
    {
      id: 16,
      name: "Olivia Clark",
      designation: "HR Manager",
      gender: "Female",
      teamName: "D",
    },
  ];  